module.exports.config = {
  name: "luatadmin",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "TuanDz",
  description: "Luật Bot",
  commandCategory: "Hệ thống admin-bot",
  usages: "",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};

module.exports.run = async({api,event,args,client,Users,Threads,__GLOBAL,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
"https://i.postimg.cc/W4bRSYxb/62eb67edabd1648f3dc010.jpg",
"https://i.postimg.cc/vTmkt4Kq/004aab23822f4d71143e8.jpg",
"https://i.postimg.cc/NG83qcYf/0mCTvKZ.jpg",
"https://i.postimg.cc/hPcqfGMd/0wizCbR.jpg",
"https://i.postimg.cc/pr17G2b2/1ffeae90879c48c2118d12.jpg",
"https://i.postimg.cc/X7q6wPSj/1P55PQ5.jpg",
"https://i.postimg.cc/qBjd6TFD/2IiqHC1.jpg",
"https://i.postimg.cc/Zq7qLd72/2mQSGKi.jpg",
"https://i.postimg.cc/tJ7W5bNt/2QZHfKi.jpg",
"https://i.postimg.cc/DZpbmD3W/2ZZrpkq.jpg",
"https://i.postimg.cc/ydhsb3v7/30ll2w8.jpg",
"https://i.postimg.cc/cCjYkzDq/3b8HVDz.jpg",
"https://i.postimg.cc/BQKJ1yfr/3DZKX4f.jpg",
"https://i.postimg.cc/MHsfMLkM/3FavLt7.jpg",
"https://i.postimg.cc/J7bLrX38/3ITbAwb.jpg",
"https://i.postimg.cc/XN2T7gZT/416dea1dc3110c4f550024.jpg",
"https://i.postimg.cc/ncCNsQBM/43e4718d588197dfce9010.jpg",
"https://i.postimg.cc/ZK226KxH/44982ae903e5ccbb95f417.jpg",
"https://i.postimg.cc/63Zy5QcP/4aO4q18.jpg",
"https://i.postimg.cc/JhbfrVJq/4oEFZjF.jpg",
"https://i.postimg.cc/3JRv53pg/4rVr3TV.jpg",
"https://i.postimg.cc/0j9H2zx5/4Uf7yOy.jpg",
"https://i.postimg.cc/rFkts5vN/4XpKFsN.jpg",
"https://i.postimg.cc/6pZScJHX/52ba66cb4fc78099d9d616.jpg",
"https://i.postimg.cc/7hTr0Cd3/5OWq207.jpg",
"https://i.postimg.cc/FKQ6nWqJ/64b725dd0cd1c38f9ac07.jpg",
"https://i.postimg.cc/xTvM36KZ/7YMf4mV.jpg",
"https://i.postimg.cc/YC7j2kLn/8HCm0cO.jpg",
"https://i.postimg.cc/Hk7GN7kF/8PdEhwN.jpg",
"https://i.postimg.cc/Tw6DZmqw/8xQWAvb.jpg",
"https://i.postimg.cc/DzqWd0kK/9FU9BmU.jpg",
"https://i.postimg.cc/ncycRx1V/9iGBRwr.jpg",
"https://i.postimg.cc/zf0NrYTg/9NHjJIr.jpg",
"https://i.postimg.cc/3ryZmjfM/A41JHAf.jpg",
"https://i.postimg.cc/tgtc0dQv/aa85e0e9c9e506bb5ff427.jpg",
"https://i.postimg.cc/Z5fZkh8y/AiQI8ji.jpg",
"https://i.postimg.cc/rwgy84ks/bDXZ7K5.jpg",
"https://i.postimg.cc/xCf49k9f/bee99398ba9475ca2c8515.jpg",
"https://i.postimg.cc/RFTxR5ZF/Bepi6cZ.jpg",
"https://i.postimg.cc/K8b766GF/bH2gLBG.jpg",
"https://i.postimg.cc/HnJdzvc7/BKC5g6y.jpg",
"https://i.postimg.cc/L5h67675/bkFA67N.jpg",
"https://i.postimg.cc/V6gdphkG/BRosV3A.jpg",
"https://i.postimg.cc/xTccptD5/c1jWpDB.jpg",
"https://i.postimg.cc/SK3nh968/C7hE9FP.jpg",
"https://i.postimg.cc/gJhP6Xfv/cEroOxo.jpg",
"https://i.postimg.cc/J4kB4P6n/cHH6rTl.jpg",
"https://i.postimg.cc/sx09dxgN/CqHx5G3.jpg",
"https://i.postimg.cc/tJfCHGQ5/Cs4MkUV.jpg",
"https://i.postimg.cc/76wNSjRm/d8yfkjL.jpg",
"https://i.postimg.cc/BZDKJmwv/dM3He80.jpg",
"https://i.postimg.cc/P5nTb4tP/dMyrPeR.jpg",
"https://i.postimg.cc/mrFndx84/DsliVjC.jpg",
"https://i.postimg.cc/PqGpwZ74/DsyUu49.jpg",
"https://i.postimg.cc/d1ZJmSTZ/dT5HoK9.jpg",
"https://i.postimg.cc/hP2Pnxgj/dztFRd7.jpg",
"https://i.postimg.cc/DypFHTd4/e5oK2ND.jpg",
"https://i.postimg.cc/rm7xQbnB/eBfPxQk.jpg",
"https://i.postimg.cc/43dcZZrC/fFinnH5.jpg",
"https://i.postimg.cc/CK3xtg0s/FgT5IvE.jpg",
"https://i.postimg.cc/C5KHQkS8/fhrnMHt.jpg",
"https://i.postimg.cc/T3yGX4C7/FKGxYuS.jpg",
"https://i.postimg.cc/rs8MXyPx/fn24mug.jpg",
"https://i.postimg.cc/qRvkhvpw/FO65fzi.jpg",
"https://i.postimg.cc/NFbCyQf6/fwM0YCo.jpg",
"https://i.postimg.cc/5yNdK7Xm/Fx6TzgQ.jpg",
"https://i.postimg.cc/wj3xjvTk/FxchIKS.jpg",
"https://i.postimg.cc/mZcP8mGw/g0XLrwK.jpg",
"https://i.postimg.cc/m2jhrJ3T/gJUiO3H.jpg",
"https://i.postimg.cc/YjKK3rBJ/gql5xEk.jpg",
"https://i.postimg.cc/JnCRx53T/gqsPMnJ.jpg",
"https://i.postimg.cc/cLGtKw2c/haopYQL.jpg",
"https://i.postimg.cc/gJg2N6g1/hJuhfT8.jpg",
"https://i.postimg.cc/rw5WgQxb/HRx6vj2.jpg",
"https://i.postimg.cc/Dz8hnY6p/i1fQVol.jpg",
"https://i.postimg.cc/ncJnB2VM/I8HytB4.jpg",
"https://i.postimg.cc/65mzFj7p/IJWR5tr.jpg",
"https://i.postimg.cc/DZPXFZBc/IMSU2FJ.jpg",
"https://i.postimg.cc/fbBVgFLH/InNKEZm.jpg",
"https://i.postimg.cc/BZCV7Bcj/iPSvMsA.jpg",
"https://i.postimg.cc/RZvfswdZ/IViRBcE.jpg",
"https://i.postimg.cc/K8CLDC1t/IxF9h6A.jpg",
"https://i.postimg.cc/SN2xfRCt/JFdiZPE.jpg",
"https://i.postimg.cc/6phqySd9/JPr6Vjv.jpg",
"https://i.postimg.cc/y8RhtV4L/JSozXDn.jpg",
"https://i.postimg.cc/7hDYHnfC/jXjhqP5.jpg",
"https://i.postimg.cc/7PQgLCqB/K8Vf1to.jpg",
"https://i.postimg.cc/q7nmssvM/KAuo1xc.jpg",
"https://i.postimg.cc/BQYw4Zzs/kgFkxpt.jpg",
"https://i.postimg.cc/7P7x5dkp/KIIWzuP.jpg",
"https://i.postimg.cc/T1rLQPWb/kU9X5uc.jpg",
"https://i.postimg.cc/7L7zsXzd/KxARtAY.jpg",
"https://i.postimg.cc/FRzYtZkh/l3gmjF9.jpg",
"https://i.postimg.cc/g08Wx693/lcffehu.jpg",
"https://i.postimg.cc/SKF0bNXR/lifdLYH.jpg",
"https://i.postimg.cc/RVkKcj6K/lIpZNy7.jpg",
"https://i.postimg.cc/WbThTTk9/llUTK6s.jpg",
"https://i.postimg.cc/GmTTtzXt/LTmfxeo.jpg",
"https://i.postimg.cc/rpC1yQpW/lywnLQh.jpg",
"https://i.postimg.cc/JnFWs367/M6ukxPZ.jpg",
"https://i.postimg.cc/L80XtP07/mDas8Gz.jpg",
"https://i.postimg.cc/hG5dt6BX/MgDGqwI.jpg",
"https://i.postimg.cc/T2rpzppL/MMYYUOv.jpg",
"https://i.postimg.cc/sXst164R/NC9Xu3c.jpg",
"https://i.postimg.cc/13MFL47c/NKjA7Kq.jpg",
"https://i.postimg.cc/ZqcNznfx/NKU66Da.jpg",
"https://i.postimg.cc/mDgHL4Jf/nmCcY9i.jpg",
"https://i.postimg.cc/cCc2QQT8/nmvSmgA.jpg",
"https://i.postimg.cc/nh9Tx47Y/NQvTGX7.jpg",
"https://i.postimg.cc/zDdkRtFF/nSdyduB.jpg",
"https://i.postimg.cc/y87Y4P22/NuBZ2ew.jpg",
"https://i.postimg.cc/HkPGZ9mw/o6AF8DO.jpg",
"https://i.postimg.cc/DzHTZdYv/oaCkjvr.jpg",
"https://i.postimg.cc/WzQFwk3T/oJUUfBX.jpg",
"https://i.postimg.cc/ydKzcYBt/ol2VDdR.jpg",
"https://i.postimg.cc/rwDZmX64/ovavB03.jpg",
"https://i.postimg.cc/wjPqyp1Y/P73sgEK.jpg",
"https://i.postimg.cc/CKVCVWwS/PycHFqC.jpg",
"https://i.postimg.cc/L4ZszhzQ/q7JUZ2Q.jpg",
"https://i.postimg.cc/c4yf3p8Y/QFtwH3u.jpg",
"https://i.postimg.cc/GmptTKzG/QmeOeAm.jpg",
"https://i.postimg.cc/ZYDqNpBd/QN1SzhB.jpg",
"https://i.postimg.cc/vHrHNj2W/rBlFtcn.jpg",
"https://i.postimg.cc/9fMmzfmp/RUKKFsZ.jpg",
"https://i.postimg.cc/QdN9khNB/s1Mi1wX.jpg",
"https://i.postimg.cc/DzX21MGJ/ScNfipI.jpg",
"https://i.postimg.cc/KjcJhCrR/sf6bGUi.jpg",
"https://i.postimg.cc/Gh8vTc2b/SFXLEQM.jpg",
"https://i.postimg.cc/tJV7J4zf/sh8zM3d.jpg",
"https://i.postimg.cc/fTr0M1j1/sIDlURq.jpg",
"https://i.postimg.cc/hvHg58TZ/SiudRTz.jpg",
"https://i.postimg.cc/W301cHbL/SVnb6eI.jpg",
"https://i.postimg.cc/qMRjbVvF/t3LRpAd.jpg",
"https://i.postimg.cc/RVNL17P5/TavhaCC.jpg",
"https://i.postimg.cc/c4zyTc0Q/u8CEGaU.jpg",
"https://i.postimg.cc/Jn5PgRXf/UE2x39t.jpg",
"https://i.postimg.cc/FRkJdprD/UY2vZLH.jpg",
"https://i.postimg.cc/Z51mYxQT/v8hq0BG.jpg",
"https://i.postimg.cc/W4WMJtMb/VL9DQxu.jpg",
"https://i.postimg.cc/MT5m5d2x/w8jNdWT.jpg",
"https://i.postimg.cc/m28Kkytv/wrmnTLB.jpg",
"https://i.postimg.cc/8cFfvHTZ/wTSnzSX.jpg",
"https://i.postimg.cc/YShvZRWM/wzvAdVR.jpg",
"https://i.postimg.cc/wxP6MzZ5/xFo96Mf.jpg",
"https://i.postimg.cc/t4r1Bw7B/XjlRI28.jpg",
"https://i.postimg.cc/525Y8jMW/xqymKfp.jpg",
"https://i.postimg.cc/C5NMznqc/ye4089A.jpg",
"https://i.postimg.cc/Bb3RLh50/YNd3cfi.jpg",
"https://i.postimg.cc/kGrqjFx1/yrDSC9C.jpg",
"https://i.postimg.cc/BvQT62PV/yzbZi9Z.jpg",
"https://i.postimg.cc/SsPJmMcC/Zd1dzsJ.jpg",
"https://i.postimg.cc/rsSc70j8/ZeAifCC.jpg",
"https://i.postimg.cc/66H8hFST/zWm8WwA.jpg",
  ];
	  var callback = () => api.sendMessage({body:`𝐂𝐚́𝐜 𝐥𝐮𝐚̣̂𝐭 𝐥𝐞̣̂ 𝐝𝐚̀𝐧𝐡 𝐜𝐡𝐨 𝐚𝐝𝐦𝐢𝐧 𝐭𝐡𝐮𝐞̂
- 𝐋𝐮𝐚̣̂𝐭 𝐜𝐡𝐨 𝐠𝐨́𝐢 𝟐𝟎𝐤:
+ 𝐂𝐡𝐢̉ đ𝐮̛𝐨̛̣𝐜 𝐩𝐡𝐞́𝐩 𝐭𝐡𝐞̂𝐦 𝐛𝐨𝐭 𝐯𝐚̀𝐨 𝟏 𝐧𝐡𝐨́𝐦, 𝐭𝐡𝐞̂𝐦 𝐯𝐚̀𝐨 𝐧𝐡𝐨́𝐦 𝐭𝐡𝐮̛́ 𝟐 𝐬𝐞̃ 𝐭𝐢́𝐧𝐡 𝐥𝐚̀ 𝐯𝐢 𝐩𝐡𝐚̣𝐦 𝐪𝐮𝐲 𝐜𝐡𝐞̂́ 𝐒𝐚𝐰𝐞𝐧 𝐏𝐫𝐨𝐣𝐞𝐜𝐭!
+ 𝐍𝐠𝐡𝐢𝐞̂𝐦 𝐜𝐚̂́𝐦 𝐝𝐮̀𝐧𝐠 𝐥𝐞̣̂𝐧𝐡 /𝐭𝐡𝐚𝐦𝐠𝐢𝐚 đ𝐞̂̉ 𝐯𝐚̀𝐨 𝐜𝐚́𝐜 𝐛𝐨𝐱 𝐤𝐡𝐚́𝐜
+ 𝐊𝐡𝐨̂𝐧𝐠 đ𝐮̛𝐨̛̣𝐜 𝐩𝐡𝐞́𝐩 𝐬𝐮̛̉ 𝐝𝐮̣𝐧𝐠 𝐜𝐚́𝐜 𝐥𝐞̣̂𝐧𝐡 𝐝𝐚̀𝐧𝐡 𝐜𝐡𝐨 𝐎𝐰𝐧𝐞𝐫 𝐡𝐨𝐚̣̆𝐜 𝐀𝐝𝐦𝐢𝐧 𝐠𝐨́𝐢 𝐜𝐚𝐨 𝐡𝐨̛𝐧
+ 𝐊𝐡𝐨̂𝐧𝐠 đ𝐮̛𝐨̛̣𝐜 𝐩𝐡𝐞́𝐩 𝐭𝐮̛̣ 𝐭𝐢𝐞̣̂𝐧 𝐛𝐚𝐧 𝐧𝐠𝐮̛𝐨̛̀𝐢 𝐝𝐮̀𝐧𝐠 𝐤𝐡𝐢 𝐜𝐡𝐮̛𝐚 𝐜𝐨́ 𝐥𝐲́ 𝐝𝐨 𝐛𝐚𝐧 𝐜𝐡𝐢́𝐧𝐡 đ𝐚́𝐧𝐠
+ 𝐊𝐡𝐨̂𝐧𝐠 𝐜𝐡𝐮̛̉𝐢 𝐛𝐨𝐭
- 𝐋𝐮𝐚̣̂𝐭 𝐜𝐡𝐨 𝐠𝐨́𝐢 𝟓𝟎𝐤:
+ 𝐊𝐡𝐨̂𝐧𝐠 đ𝐮̛𝐨̛̣𝐜 𝐩𝐡𝐞́𝐩 𝐬𝐨̛̀ 𝐯𝐚̀𝐨 𝐧𝐡𝐮̛̃𝐧𝐠 𝐥𝐞̣̂𝐧𝐡 𝐝𝐚̀𝐧𝐡 𝐜𝐡𝐨 𝐎𝐰𝐧𝐞𝐫
+ Đ𝐀̣̆𝐂 𝐁𝐈𝐄̣̂𝐓 𝐂𝐀̂́𝐌 Đ𝐔̣𝐍𝐆 𝐕𝐀̀𝐎 𝐂𝐀́𝐂 𝐋𝐄̣̂𝐍𝐇 𝐋𝐀̂́𝐘 𝐂𝐎𝐃𝐄 𝐌𝐎𝐃𝐔𝐋𝐄
+ 𝐂𝐨̂́ 𝐭𝐢̀𝐧𝐡 𝐜𝐡𝐮̛̉𝐢 𝐛𝐨𝐭 𝐬𝐞̃ 𝐭𝐚́𝐧𝐠 𝐭𝐡𝐚̆̉𝐧𝐠 𝐯𝐚̀𝐨 𝐦𝐨̃𝐦 :))
𝐇𝐚̃𝐲 𝐭𝐫𝐨̛̉ 𝐭𝐡𝐚̀𝐧𝐡 𝐦𝐨̣̂𝐭 𝐧𝐠𝐮̛𝐨̛̀𝐢 𝐜𝐨́ 𝐲́ 𝐭𝐡𝐮̛́𝐜 𝐯𝐚̀ 𝐜𝐡𝐚̂́𝐩 𝐡𝐚̀𝐧𝐡 𝐧𝐠𝐡𝐢𝐞̂𝐦 𝐜𝐡𝐢̉𝐧𝐡 𝐪𝐮𝐲 𝐜𝐡𝐞̂́, 𝐧𝐞̂́𝐮 𝐜𝐨̂́ 𝐭𝐢̀𝐧𝐡 𝐬𝐞̃ 𝐡𝐚̣ 𝐭𝐡𝐚̆̉𝐧𝐠 𝐪𝐮𝐲𝐞̂̀𝐧 𝐚𝐝𝐦𝐢𝐧 𝐯𝐚̀ 𝐤𝐡𝐨̂𝐧𝐠 𝐡𝐨𝐚̀𝐧 𝐭𝐢𝐞̂̀𝐧!`,attachment: fs.createReadStream(__dirname + "/cache/5.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/5.jpg")); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/5.jpg")).on("close",() => callback());
   };